### ISSUE TITLE
What to do about IE8

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery-old#193]
Since this ships as is in 8.0 and it is not going to get updated for 8.1, a message akin to the one being displayed when no pictures are found should be displayed to Internet Explorer users, letting them know that their browser is not compatible with the app, or maybe the app should be removed from the menu (that might confuse users who install the app and don't see it in the menu).
These users will still be able to use the slidesow on the Files side and will, of course, be able to access the app when using either Firefox, Chrome or their mobile browser.

**Comment by oparoz** [comment]
@icewind1991 @jancborchardt @karlitschek

**Comment by gsosna** [comment]
For these people who want their owncloud gallery to be accessible to everyone, regardless of OC developer beliefs of an utopian world without IE, here is hack you can easily add to force people on IE to folder view - at least they can see the files and they can still run slideshow:

in /var/www/owncloud/.htacccess

Under section

  <IfModule mod_rewrite.c>
  RewriteEngine on

add 4 lines:

  #below 3 lines redirect IE users to file view
  RewriteCond %{HTTP_USER_AGENT} "MSIE " [NC,OR]
  RewriteCond %{HTTP_USER_AGENT} "rv:1" [NC]
  RewriteRule ^index.php/apps/gallery/public/(.*)$ /index.php/s/$1 [R=301,L]

**Comment by oparoz** [comment]
That could be a quick solution for the next maintenance releases of 8 and 8.1.

For 8.2, we should seek a more elegant solution where the app doesn't appear in the app menu.

**Comment by jancborchardt** [comment]
cc @DeepDiver1975 @cmonteroluque @karlitschek regarding Gallery and IE discussion.

**Comment by karlitschek** [comment]
@MTRichards

**Comment by MTRichards** [comment]
Very clever thought....but, errrr...not the most practical for our user base. :confounded:

**Comment by oparoz** [comment]
> Very clever thought....but, errrr...not the most practical for our user base

@MTRichards - The htaccess directive or the whole approach?

**Comment by jancborchardt** [comment]
Well, instead of disabling it we should try to fix it. @LukasReschke’s https://github.com/owncloud/gallery/pull/206 is a first attempt at doing so – please review @oparoz @gsosna

**Comment by oparoz** [comment]
Redirecting for all IE versions should be the first step, while we wait for potential fixes. You can then selectively enable the app back. You need to be pro-active, as it simply gives a bad image of ownCloud when you ship broken apps as it's been the case for the past 6 months.

But I wouldn't try to fix anything in this repo. There are simply too many issues with that code.

**Comment by gsosna** [comment]
@oparoz I completely agree - for me that's especially the publicly shared links. I sent a link to friends and family of an album, and people on IE tell me that it's not working. That's why I have the redirect. 

I can confirm that @LukasReschke’s #206 commit 6310209 fixes the issue for IE9, 10 & 11. I will keep my redirect for IE7 & 8 to maintain compatibility for publicly shared albums for people who refuse to update...

in /var/www/owncloud/.htaccess under RewriteEngine on:

RewriteCond %{HTTP_USER_AGENT} "MSIE 7" [NC,OR]
RewriteCond %{HTTP_USER_AGENT} "MSIE 8" [NC,OR]
RewriteRule ^index.php/apps/gallery/public/(.*)$ /index.php/s/$1 [R=302,L]

**Comment by davitol** [comment]
:+1: Gallery app 0.6.1. 
browser: Internet Explorer 11.0.9600.17843
OC server: version":"8.1.0.8","versionstring":"8.1.0","edition"

**Comment by DeepDiver1975** [comment]
> :+1: Gallery app 0.6.1.

? I assume you are talking about the code as proposed in #206 - right ?

**Comment by davitol** [comment]
That's right @DeepDiver1975

**Comment by oparoz** [comment]
You can't close this yet as #206 does not work on our beloved IE8 and since it's not been tested on XP and Vista.

For IE8, there needs to be a redirection, either via .htaccess or via Javascript.

**Comment by davitol** [comment]
Tested in windows 2008 server with IE8 does not work
IE9 works fine and also in IE11 as I said before

**Comment by jancborchardt** [comment]
So is there any way we can fix this for IE8 which is not disabling the app?

**Comment by oparoz** [comment]
That would probably require fixing `core` or using a polyfill instead of custom sauce. I'm surprised it works for IE9, but not for IE8 as they usually use the same fallback. Maybe it can be easily fixed by the person who wrote the PHP code, but those changes have an impact on more than just Pictures.

**Comment by jancborchardt** [comment]
@LukasReschke @DeepDiver1975 we shall take care of that then – please do what’s necessary.

**Comment by oparoz** [comment]
There is already a ticket for it. I've updated it to reflect the current situation.
https://github.com/owncloud/core/issues/15599

**Comment by oparoz** [comment]
I've got news regarding IE8. The browser can't handle Data URIs larger than 32KB, which means it will choke on some of the base64 encoded thumbnails we send back and fixing the polyfill will not help.

So 3 solutions:

* Message in Gallery, telling the user he can't see his images with this browser
* No Gallery app button, so user can only use the slideshow
* Someone writes a new thumbnail fetcher just for IE8

**Comment by gsosna** [comment]
Please consider that the gallery app is also available to public via link eg. https://owncloud/index.php/apps/gallery/public/KJOIUP9ou899y, which isn't as easy as "hiding the app button" - so a redirect is necessary for these cases. For the logged in users, a message to advise that anything below IE9 is not supported in the gallery app is more appropriate.

**Comment by oparoz** [comment]
Thanks for your feedback :)

I've modified the 3rd option. It's now described in https://github.com/owncloud/galleryplus/issues/228

I'll let the product manager decide what's best for ownCloud

**Comment by jancborchardt** [comment]
@karlitschek @cmonteroluque @MTRichards @DeepDiver1975 so which of the 3 solutions @oparoz proposes in https://github.com/owncloud/gallery/issues/193#issuecomment-124560493 do we want to go for?

**Comment by jancborchardt** [comment]
@oparoz maybe we should move the remaining relevant stuff from here to https://github.com/owncloud/gallery/issues/228 so we can close this last open issue in the gallery-old issue tracker? (And then we have all the IE8 stuff in one place) :)

**Comment by oparoz** [comment]
Done. https://github.com/owncloud/gallery/issues/249
