### ISSUE TITLE
Change pictures view button is not visible using IE11 as browser

### ISSUE THREAD

**Issue by davitol** [owncloud/gallery-old#209]
### Steps to reproduce
1. Using IE 11 as browser, go to Pictures menu
2. Share the pictures by link
3. Using the previous link change the view of the pictures

### Expected behaviour
The change view button should be more visible and not located just in the right

### Actual behaviour
The button is only half-visible due to the slide bar 

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.4

**ownCloud version:** OC 8.1.0.8

**Updated from an older ownCloud or fresh install:** fresh install

![share1](https://cloud.githubusercontent.com/assets/10596560/8823441/087f446e-306d-11e5-8f7c-fb234020aed7.jpg)
![share2](https://cloud.githubusercontent.com/assets/10596560/8823462/4f779e2a-306d-11e5-8577-307589f85bbe.jpg)

**Comment by oparoz** [comment]
It's not a problem with the new Gallery as the scrollbar slides underneath the button, but I'll let @jancborchardt decide if he wants to fix Pictures, in which case this issue should probably be cloned in https://github.com/owncloud/galleryplus/issues

**Comment by jancborchardt** [comment]
What’s up with this crazy new IE scrollbar? It overlays the whole right part. @davitol is it only visible when hovering on the right, or all the time?

**Comment by jancborchardt** [comment]
As you can see from overlaying the header bar (such as username and the other buttons), this seems to be intended behavior of IE.
